Merging the extra.gradle file into build.gradle (6)
cuba-labs/restapi-demo pull request #7
Opened 2019-06-07 14:20 UTC by NikitaShchienko

2019-06-07 19:22 UTC, dtsaryov commented on build.gradle
> +task enableRemoteJmx() {
Проверь, действительно ли нам нужны эти таски - вроде можно без них обойтись

2019-06-07 19:22 UTC, dtsaryov commented on build.gradle
> +task enableTestProperties() {
И эта таска

2019-06-07 19:23 UTC, dtsaryov commented on build.gradle
> +task stopTomcatAfterTest(type: CubaStopTomcat, description: 'Stops Tomcat after functional tests') {
Не помню чтобы эта таска использовалась

2019-06-07 19:26 UTC, dtsaryov requested changes

2019-06-07 19:26 UTC, dtsaryov commented on build.gradle
> +        setupTomcat.execute()
В 7.2 Gradle обновлён до 5.4.1 - нужно все execute поменять на `depends` + `mustRunAfter` / `mustRunBefore`

2019-06-07 19:26 UTC, dtsaryov commented on build.gradle
> +        File dir = new File("$projectDir/tests/ui/out")
Это вроде тоже лишнее

2019-06-10 14:19 UTC, NikitaShchienko commented on build.gradle
> +task enableRemoteJmx() {
Таска нужна для тестов

2019-06-10 14:19 UTC, NikitaShchienko commented on build.gradle
> +task enableTestProperties() {
Таска нужна для тестов

2019-06-10 16:16 UTC, dtsaryov requested changes

2019-06-10 16:16 UTC, dtsaryov commented on build.gradle
> +    dependsOn setupTomcat
Уже есть секция `dependsOn` в декларации, зачем сюда-то?

2019-06-10 16:16 UTC, dtsaryov commented on build.gradle
> +    dependsOn coreModule.deploy, webModule.deploy, portalModule.deploy
То же самое - `dependsOn` уже есть, перенеси туда

2019-06-10 16:16 UTC, dtsaryov commented on build.gradle
> +    enableTestProperties.mustRunAfter(setupTomcat)
Пропиши явно после этих задач

2019-06-10 16:16 UTC, dtsaryov commented on build.gradle
> +    finalizedBy start
Обычно пишется так: `taskA.dependsOn taskB` - более понятно и очевидно

2019-06-10 16:16 UTC, dtsaryov commented on build.gradle
> +    ant.waitfor(maxwait: 30, maxwaitunit: 'second', checkevery: 2, checkeveryunit: 'second') {
А это зачем?

2019-06-10 16:16 UTC, dtsaryov commented on build.gradle
> +}
Кажется, пустой строки в конце не хватает

2019-06-11 11:51 UTC, dtsaryov requested changes

2019-06-11 11:51 UTC, dtsaryov commented on build.gradle
> +task prepareTest(dependsOn: [dropTomcat, setupTomcat, coreModule.createDb, coreModule.assemble, webModule.assemble, portalModule.assemble, configureTest, deployTest, start], description: 'Prepare ser
1. subprojects
2. deploy и так уже зависит от assemble
3. ну и нормальное форматирование

```Groovy
task prepareTest(dependsOn: [dropTomcat, setupTomcat, configureTest,
                             coreModule.createDb,
                             subprojects.deploy, start], 
        description: 'Prepare server for tests') {
}
```

2019-06-11 11:51 UTC, dtsaryov commented on build.gradle
> +task deployTest(dependsOn: [coreModule.deploy, webModule.deploy, portalModule.deploy])
Зачем?

2019-06-14 06:40 UTC, dtsaryov approved these changes

2019-06-14 06:41 UTC, merged